config/routes.rb
Rails.application.routes.draw do
  root to: 'users#index'

  resources :stories do
    resources :snippets
  end

  resources :users do
    resources :stories
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snippet.rb
class Snippet < ActiveRecord::Base

  belongs_to :story

  validates :body, :presence => true
  validates :image, :presence => true
  
end

app/models/story.rb
class Story < ActiveRecord::Base

  belongs_to :user
  has_many :snippets

  validates :title, :presence => true

end

app/models/user.rb
class User < ActiveRecord::Base

  has_many :stories
  has_many :snippets

  validates :name, :presence => true

  scope :alphabetical, -> { order(name: :asc) }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/snippets_controller.rb
class SnippetsController < ApplicationController

  def new
    @story = Story.find(params[:story_id])
    @snippet = Snippet.new
  end

  def create
    @story = Story.find(params[:story_id])
    @snippet = @story.snippets.new(snippet_params)
    if @snippet.save
      flash[:notice] = "Snippet saved!"
      redirect_to story_path(@snippet.story)
    else
      render :new
    end
  end

  private
  def snippet_params
    params.require(:snippet).permit(:body, :image)
  end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController

  def index
    @stories = Story.all
  end

  def show
    @story = Story.find(params[:id])
  end

  def new
    @user = User.find(params[:user_id])
    @story = @user.stories.new
  end

  def create
    @user = User.find(params[:user_id])
    @story = @user.stories.new(story_params)
    if @story.save
      flash[:notice] = "Story added!"
      redirect_to user_story_path(@user, @story)
    else
      render :new
    end
  end

  private
  def story_params
    params.require(:story).permit(:title)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.alphabetical
  end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:notice] = "User saved!"
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_controller?(names)
    myPath = request.path
    myPath.include?(names)
  end
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>StoryTime</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <div class="container">
      <div id="crouton">
        <ul class="lesson-nav">
          <li> <%= link_to "Home", root_path %> </li>
          <li> <%= link_to "Add User", new_user_path %> </li>
          <% if current_controller?('users') && !@user.nil? && @story.nil? %>
            <% if current_controller?('new')%>
            <% else %>
              <li> <%= link_to "Add Story", new_user_story_path(@user.id) %> </li>
            <% end %>
          <% end %>
          <% if current_controller?('stories') && !@story.nil? %>
            <li> <%= link_to "Add Story", new_user_story_path(@story.user_id) %> </li>
            <% if current_controller?('stories') %>
              <% if current_controller?('new') %>
              <% else %>
                <li> <%= link_to "Add Snippet", new_story_snippet_path(@story.id) %> </li>
              <% end %>
            <% end %>
          <% end %>
        </ul>
      </div>

      <%= yield %>
    </div>

  </body>
</html>

app/views/snippets/_form.html.erb
<%= render('layouts/errors', :object => @snippet) %>

<%= form_for [@story, @snippet] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <br><br>
  <%= f.label :image %>
  <%= f.text_field :image %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>

app/views/snippets/new.html.erb
<h1>New Snippet</h1>

<%= render 'form' %>

app/views/stories/_form.html.erb
<%= render('layouts/errors', :object => @story) %>

<%= form_for [@user, @story] do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>

app/views/stories/new.html.erb
<h1>New Story</h1>

<%= render 'form' %>

app/views/stories/show.html.erb
<h1> <%= @story.title %> </h1>

<ul>
  <% @story.snippets.each do |snippet|  %>
    <li><p> <%= snippet.body %> </p></li>
  <% end %>
</ul>

app/views/users/_form.html.erb
<%= render('layouts/errors', :object => @user ) %>

<%= form_for [@user] do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <p><%= f.submit %></p>
<% end %>

app/views/users/index.html.erb
<h1>all users</h1>

<ul>
  <% @users.each do |user|  %>
    <li> <%= link_to user.name, user_path(user) %> </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form' %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<ul>
  <% @user.stories.each do |story|  %>
    <li> <%= link_to story.title, story_path(story) %> </li>
  <% end %>
</ul>